package com.mnassa.screen.notifications

/**
 * Created by IntelliJ IDEA.
 * User: okli
 * Date: 4/16/2018
 */

const val privateChatMessage = "privateChatMessage"
const val responseChatMessage = "responseChatMessage"
const val postComment = "postComment"
const val connectionRequest = "connectionRequest"
const val postRepost = "postRepost"
const val newUserJoined = "newUserJoined"
const val iWasRecommended = "iWasRecommended"
const val iWasRecommendedInEvent = "iWasRecommendedInEvent"
const val userWasRecommended = "userWasRecommended"
const val userWasRecommendedByPost = "userWasRecommendedByPost"
const val generalPostByAdmin = "generalPostByAdmin"
const val newEventAttendee = "newEventAttendee"
const val eventCancelling = "eventCancelling"
const val autoSuggestYouCanHelp = "autoSuggestYouCanHelp"
const val newEventByAdmin = "newEventByAdmin"
const val invitesNumberChanged = "invitesNumberChanged"
const val connectionsRequestAccepted = "connectionsRequestAccepted"
const val userWasRecommendedToYou = "userWasRecommendedToYou"
const val userWasRecommendedInEvent = "userWasRecommendedInEvent"
const val postPromoted = "postPromoted"
const val oneDayToExpirationOfPost = "oneDayToExpirationOfPost"
const val postIsExpired = "postIsExpired"

const val BASE_KEY = "_notification_text_key"

const val COMMENTED_POST = "_commented_post"
const val REQUESTED_CONNECT = "_requested_connect"
const val REPOSTED_POST = "_reposted_post"
const val BECAME_MNASSA_USER = "_become_mnassa_user"
const val RECOMMENDED_YOU_IN_POST = "_recommended_you_in_post"
const val RECOMMENDED_YOU_IN_EVENT = "_recommended_you_in_event"
const val RECOMMENDED_YOU = "_recommended_you"
const val FOR = "_for"
const val ANNOUNCED_YOU = "_announcedYou"
const val GENERAL_POST_BY_ADMIN = "_generalPostByAdmin"
const val NEW_EVENT_ATTENDEE = "_newEventAttendee"
const val YOU_CAN_HELP = "_youCanHelp"
const val INVITE_TO_EVENT = "_inviteToEvent"
const val NUMBER_OF_INVITATIONS = "_numberOfInvitations"
const val NUMBER_OF_INVITATIONS_TAIL = "_numberOfInvitationsTail"
const val CONNECTION_REQUEST_WAS_ACCEPTED = "_connectionRequestWasAccepted"
const val USER_WAS_RECOMENDED_TO_YOU = "_userWasRecommendedToYou"
const val USER_WAS_RECOMENDED_TO_YOU_IN_EVENT = "_userWasRecommendedToYouInEvent"
const val USER_WAS_RECOMENDED_TO_YOU_IN_EVENT_2 = "_userWasRecommendedToYouInEvent2"
const val EVENT_WAS_CANCELLED = "_eventWasCancelled"
const val EVENT_WAS_CANCELLED_POINTS_RETURNING = "_eventWasCancelledPointsReturning"


const val COMMENTED_POST_I_NEED = "I need "
const val COMMENTED_POST_DEFAULT_VALUE = "Commented your post"
const val REQUESTED_CONNECT_DEFAULT_VALUE = "Requested to connect with you"
const val REPOSTED_POST_DEFAULT_VALUE = "reposted your post"
const val BECAME_MNASSA_USER_DEFAULT_VALUE = "become new MNASSA user"
const val RECOMMENDED_YOU_IN_POST_DEFAULT_VALUE = "Recommended you in post"
const val RECOMMENDED_YOU_IN_EVENT_DEFAULT_VALUE = "Recommended you in event"
const val RECOMMENDED_YOU_DEFAULT_VALUE = "Recommended you"
const val FOR_DEFAULT_VALUE = "for"
const val ANNOUNCED_YOU_DEFAULT_VALUE = "Announced your profile"
const val GENERAL_POST_BY_ADMIN_DEFAULT_VALUE = "Put your attention on post "
const val NEW_EVENT_ATTENDEE_DEFAULT_VALUE = "is going to attend"
const val YOU_CAN_HELP_DEFAULT_VALUE = "It seems you can help."
const val INVITE_TO_EVENT_DEFAULT_VALUE = "invited you to"
const val NUMBER_OF_INVITATIONS_DEFAULT_VALUE = "You can send"
const val NUMBER_OF_INVITATIONS_TAIL_DEFAULT_VALUE = "more invites."
const val CONNECTION_REQUEST_WAS_ACCEPTED_DEFAULT_VALUE = "Requested to connect with you"
const val USER_WAS_RECOMENDED_TO_YOU_DEFAULT_VALUE = "Recommended you"
const val USER_WAS_RECOMENDED_TO_YOU_IN_EVENT_DEFAULT_VALUE = "Thinks"
const val USER_WAS_RECOMENDED_TO_YOU_IN_EVENT_2_DEFAULT_VALUE = "can help you with"
const val YOU_PROMOTED_YOUR_POST_DEFAULT_VALUE = "You promoted own post:"
const val YOUR_POST_WILL_EXPIRE_TOMORROW_DEFAULT_VALUE = "Your post will expire tomorrow. Prolong it or it will be closed."
const val YOUR_POST_WAS_EXPIRED_DEFAULT_VALUE = "Your post has expired"
const val EVENT_WAS_CANCELLED_DEFAULT_VALUE = "was cancelled by organizer."
const val EVENT_WAS_CANCELLED_POINTS_RETURNING_DEFAULT_VALUE = "point(s) were returned."
